ARG DEBIAN_DIST=bookworm
FROM debian:$DEBIAN_DIST

ARG DEBIAN_DIST
ARG television_VERSION
ARG BUILD_VERSION
ARG FULL_VERSION
ARG ARCH
ARG TV_RELEASE
ARG PACKAGE_DEPENDS=""

RUN mkdir -p /output/usr/bin
RUN mkdir -p /output/usr/share/doc/television
RUN mkdir -p /output/usr/share/man/man1
RUN mkdir -p /output/usr/share/bash-completion/completions
RUN mkdir -p /output/usr/share/fish/vendor_completions.d
RUN mkdir -p /output/usr/share/zsh/vendor-completions
RUN mkdir -p /output/DEBIAN

# Upstream names the binary "tv"; the package is named after the project.
COPY ${TV_RELEASE}/tv /output/usr/bin/tv
COPY ${TV_RELEASE}/doc/tv.1 /output/usr/share/man/man1/tv.1
# Completions are generated by build_*.sh from the amd64 binary (they are
# architecture independent) and installed under the BINARY name, not the
# package name.
COPY completions/tv.bash /output/usr/share/bash-completion/completions/tv
COPY completions/tv.fish /output/usr/share/fish/vendor_completions.d/tv.fish
COPY completions/_tv /output/usr/share/zsh/vendor-completions/_tv
RUN chmod 755 /output/usr/bin/tv
RUN gzip -9n /output/usr/share/man/man1/*.1
COPY output/DEBIAN/control /output/DEBIAN/
COPY output/DEBIAN/postinst /output/DEBIAN/postinst
RUN chmod 755 /output/DEBIAN/postinst
COPY output/copyright /output/usr/share/doc/television/
COPY output/changelog.Debian /output/usr/share/doc/television/
COPY output/README.md /output/usr/share/doc/television/

RUN sed -i "s/DIST/$DEBIAN_DIST/" /output/usr/share/doc/television/changelog.Debian
RUN sed -i "s/FULL_VERSION/$FULL_VERSION/" /output/usr/share/doc/television/changelog.Debian
RUN sed -i "s/DIST/$DEBIAN_DIST/" /output/DEBIAN/control
RUN sed -i "s/television_VERSION/$television_VERSION/" /output/DEBIAN/control
RUN sed -i "s/BUILD_VERSION/$BUILD_VERSION/" /output/DEBIAN/control
RUN sed -i "s/SUPPORTED_ARCHITECTURES/$ARCH/" /output/DEBIAN/control
# amd64 ships the statically linked musl build and needs no dependencies; the
# arm64/i386 builds are glibc-linked, so they declare libc6/libgcc-s1.
RUN if [ -n "$PACKAGE_DEPENDS" ]; then \
        sed -i "s|^PACKAGE_DEPENDS$|Depends: $PACKAGE_DEPENDS|" /output/DEBIAN/control; \
    else \
        sed -i "/^PACKAGE_DEPENDS$/d" /output/DEBIAN/control; \
    fi

RUN dpkg-deb --build /output /television_${FULL_VERSION}.deb
